org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-powah
addon_name=BlueMap Powah Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-powah-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=36572
accepted_jar_sha256=0b370dfcd5d8c0a5844dd920d60a2cdb74ed441d87ff038382d8292c374686c8
